### PR TITLE
Add Carousel component

### PR DESCRIPTION
**Pull request by raaaahman**
## Changes

This PR aims to add the a Carousel component similar to the [one from the Tailwind Elements library](https://tailwind-elements.com/docs/standard/components/carousel/).

It also aims to implements the [Carousel Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/carousel/) from the WAI-ARIA Authoring Practice guide.

This PR is in draft mode in order to start a discussion related to #12 

## To Do (not exhaustive)

- [ ] Support all the options from [TE Carousel API](https://tailwind-elements.com/docs/standard/components/carousel/#docsTabsAPI)
  - [ ] pause
  - [ ] ride
  - [ ] wrap
- [ ] ? Implement a Rotation Control (as described by WAI-ARIA)
- [ ] ? Exports the context providers for programmtically interacting with a Carousel component 
- [ ] ? Supports the fade animation (alternative option: see below)

## Going further

- [ ] ? Extract the swipe controls in a custom hook for usage in other components
- [ ] ? Use the future Animation component to handle slide transition

### CODE REVIEW

**Comment by juujisai** [comment]
@cla-bot check

**Comment by juujisai** [comment]
Thank you for your PR! We'll take a look when we can. Let us know if you are working on any other components so we won't work on the same components 😄

**Comment by raaaahman** [comment]
I could open other draft PRs for Dropdown and Animation as well. These are smaller components (Dropdown at leadt is), so maybe I should complete them and open complete PRs instead. Is any task not labeled 'In Progress' in the Project view safe to work on?

**Comment by juujisai** [comment]
If task is not assigned to anyone then its fine otherwise it's better to ask because maybe we are already working on it. If you would like to create a PR for a task that is not already assigned to anyone then let me know and I will add you

**Comment by juujisai** [comment]
Hey there! Apologies for the delay in getting back to you. After taking a closer look, our team thought it would be more convenient to build the carousel component from scratch on our end. We've got some code from a previous project that we can use as a starting point, making it simpler to add the remaining options and manage the component down the line.

Thanks for your valuable contribution and effort.

**Comment by raaaahman** [comment]
No worry, thank you for letting me know.

**Pull request closed without merging**
